<a href="https://colab.research.google.com/github/rkaclfdl123/NLP_practice/blob/main/Bag_of_Words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## OKT 형태소 분석기

In [ ]:
#예시
text = "한글 자연어 처리는 재밌다. 이제부터 열심히 해야지ㅎㅎㅎㅎ"

print(okt.morphs(text))
print(okt.morphs(text, stem = True)) #stem = True 옵션으로

['한글', '자연어', '처리', '는', '재밌다', '.', '이제', '부터', '열심히', '해야지', 'ㅎㅎㅎㅎ']
['한글', '자연어', '처리', '는', '재밌다', '.', '이제', '부터', '열심히', '하다', 'ㅎㅎㅎㅎ']


해야지 >> 하다 어간으로 바뀜
<br>
<br>
<br>
<br>
<br>







##Bag of Words
- 단어의 등장순서를 고려하지 않은 빈도수 기반의 단어 표현 방법임.
- 분류 문제나 문서간의 유사도를 구하는 문제에 쓰임.

<br>
<br>
<br>

## 동작 방식

### 1. 각 단어에 고유한 정수 인덱스 부여
### 2. 각 인덱스의 위치에 단어 토큰의 등장 횟수를 기록한 벡터 생성

In [ ]:
!pip install konlpy
from konlpy.tag import Okt
import re  
okt = Okt()  

# 정규 표현식을 통해 온점을 제거하는 정제 작업.  
token = re.sub("(\.)","","정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다.")  

# OKT 형태소 분석기를 통해 토큰화 작업을 수행한 뒤에, token에다가 넣음.  
token = okt.morphs(token)  


In [ ]:
token

['정부', '가', '발표', '하는', '물가상승률', '과', '소비자', '가', '느끼는', '물가상승률', '은', '다르다']

In [ ]:

word2index = {}  
bow = []  
for voca in token:  
# token을 읽으면서, word2index에 없는 (not in) 단어는 새로 추가하고, 이미 있는 단어는 넘깁니다.   
         if voca not in word2index.keys():  
             word2index[voca] = len(word2index)  
             # BoW 전체에 전부 기본값 1을 넣는다.
             bow.insert(len(word2index)-1,1)
         else:
            # 재등장하는 단어의 인덱스
            index = word2index.get(voca)

            # 재등장한 단어는 해당하는 인덱스의 위치에 1을 더한다.
            bow[index] = bow[index]+1

print(word2index)  

{'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}


In [ ]:
bow # 가, 물가상승률이 2번씩 나옴

[1, 2, 1, 1, 2, 1, 1, 1, 1, 1]

## CountVectorizer 클래스로 BoW 만들기
- 사이킷 런 CountVectorizer 로 BOW 만들기

<br>
<br>
<br>
<br>


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['you know I want your love. because I love you.']
vector = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
print(vector.fit_transform(corpus).toarray()) 

# 각 단어의 인덱스가 어떻게 부여되었는지를 출력
print(vector.vocabulary_) 


[[1 1 2 1 2 1]]
{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


In [ ]:
print(vector.fit_transform(corpus))

  (0, 4)	2
  (0, 1)	1
  (0, 3)	1
  (0, 5)	1
  (0, 2)	2
  (0, 0)	1


In [ ]:
# 사용자가 직접 정의한 불용어 사용
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords

text = ["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)


[[1 1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


In [ ]:
# CountVectorizer 라이브러리에서 제공하는 자체 불용어 사용
text = ["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words="english")
print(vect.fit_transform(text).toarray())
print(vect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}
